# Retrospectiva 

## SPRINT 1

### En este sprint hicimos bien: 
Creamos los wireframes con pespectivas tanto celular como pantallas más grandes. Mantuvimos comunicación constante y fluida. 

### En el sprint anterior hicimos mal:
No organizamos bien el tiempo.

### Para el proximo sprint deberíamos empezar a hacer: 
Organizarnos más rapido y designar mejor los deberes de cada persona. 

### Para el proximo sprint deberíamos dejar de hacer:
Dejar de posponer las reuniones. 


## SPRINT 2

### En este sprint hicimos bien:
Creamos los html con un diseño responsive.  

### En el sprint anterior hicimos mal:
No organizamos bien el tiempo 

### Para el proximo sprint deberíamos empezar a hacer:
Organizarnos más rapido y designar mejor los deberes de cada persona. 

### Para el proximo sprint deberíamos dejar de hacer: 
Dejar de posponer las reuniones.


## SPRINT 3

### En este sprint hicimos bien:
Creamos las diferentes vistas en EJS y se incluyeron las que se repiten (head, header y footer) en las otras vistas.

### En el sprint anterior hicimos mal:
La organización del tiempo ha sido una área de oportunidad recurrente en el equipo, debido a que los tres realizamos otras actividades tanto académicas como laborales.

### Para el proximo sprint deberíamos empezar a hacer:
Orginzar mejor tanto el tiempo como las responsabilidades, y asignar las actividades teniendo en cuenta las capacidades y fortalezas de cada miembro.

### Para el proximo sprint deberíamos dejar de hacer: 
Posponer las reuniones.


## SPRINT 4

### En este sprint hicimos bien:
Continuar haciendo los sprints, evitando generar retrasos en las entregas.

### En el sprint anterior hicimos mal:
Retrasos en el sprint 4 y 5 dejando varios dias inactivo el proyecto.

### Para el proximo sprint deberíamos empezar a hacer:
Regresar a implementar las reunión daily o weekly, últimamente por motivos universitarios hemos detenido las reuniones diarias o semanales por lo que es buena idea volver a encontrar espacio para exponer cada quien dudas o impedimentos en los puntos requeridos de los sprints.

### Para el proximo sprint deberíamos dejar de hacer: 
Ir posponiendo entregas de los puntos requeridos en cada sprint o las reuniones weekly igualmente dejar de posponerlas.


## SPRINT 5

### En este sprint hicimos bien:
El formulario de resgisto con los campos mínimos, la opción para cargar una imagen de perfil y el guarado encriptado de las contraseñas en formato JSON. Además, se realizó el formulario de login y se incluyó el campo de email y password. Por último, se establecieron las rutas de huéspedes y usuarios.

### En el sprint anterior hicimos mal:
Retrasos con la entrega de este sprint y dejar por varios dias inactivo el proyecto.

### Para el proximo sprint deberíamos empezar a hacer:
Implementar las reunión daily o weekly.

### Para el proximo sprint deberíamos dejar de hacer: 
No posponer tanto las entregas de los sprint como las reuniones weekly.

## SPRINT 6

### En este sprint hicimos bien:
El diagrama de base de datos, el scrpit de creación de estructura de base de datos, la creación de carpeta Sequeliza y el CRUD.

### En el sprint anterior hicimos mal:
Retrasos con la entrega de este sprint.

### Para el proximo sprint deberíamos empezar a hacer:
Implementar las reunión daily o weekly.

### Para el proximo sprint deberíamos dejar de hacer: 
No posponer tanto las entregas de los sprint como las reuniones weekly.

## SPRINT 7

### En este sprint hicimos bien:
Validaciones del back-end con Express Validator, validaciones del front-end con JavaScript.

### En el sprint anterior hicimos mal:
Retrasos con la entrega de este sprint.

### Para el proximo sprint deberíamos empezar a hacer:
Implementar las reunión daily o weekly.

### Para el proximo sprint deberíamos dejar de hacer: 
No posponer tanto las entregas de los sprint como las reuniones weekly.

## SPRINT 8

### En este sprint hicimos bien:
Quizás por la promura, pero en este Sprint se trabajó más en equipo y hubo buena comunicación. Lo cual, llevó a concluir con el proyecto integrador de la mejor manera y cumplir con los objetivos.

### En el sprint anterior hicimos mal:
Los retrasos con la entrega de este sprint y de los anteriores, fue un problema que se arrastró durante todo el curso, pero entendemos que también los otros proyectos personales de cada uno demandaban de nuestra atención.

### Para el proximo sprint deberíamos empezar a hacer:
Aunque no habrá un próximo Sprint, porque este es el último, sabemos que parte del trabajo en equipo son las reunión daily o weekly.

### Para el proximo sprint deberíamos dejar de hacer: 
Para los próximos Sprints de otros proyectos, superaremos las areas de mejora que aquí se presentaron.